---

spring:
  # DATASOURCE
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: 'org.h2.Driver'
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  # SECURITY
  security:
    oauth2:
      client:
        registration:
          cesnet:
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/cesnet'
            scope: 'openid'
            client-id: 6d6d5d16-6d42-4d14-8da8-393b7268c780
            client-secret: TODO-FILL
        provider:
          cesnet:
            issuer-uri: 'https://login.cesnet.cz/oidc/'
            userNameAttribute: 'sub'

logging:
  level:
    org.springframework: debug

app:
  languages: [ 'en', 'cs' ]
  templatesLocation: "/etc/cms/templates/"
  messagesLocation: "/etc/cms/i18n/"
  apiBasicAuths:
    - username: user
      password: pass
    - username: admin
      password: admin